export interface NewsItem {
  id: string
  title: string
  excerpt: string
  date: string
  category: string
  image: string
}

export interface FeaturedRecipe {
  id: string
  title: string
  description: string
  image: string
  cookTime: string
  difficulty: string
}

export interface Recipe {
  id: string
  title: string
  description: string
  image: string
  cookTime: string
  prepTime: string
  servings: number
  difficulty: "Easy" | "Medium" | "Hard"
  cuisine: string
  dietary: string[]
  ingredients: string[]
  instructions: string[]
  author: string
  rating: number
  reviews: number
}

export const newsItems: NewsItem[] = [
  {
    id: "1",
    title: "Summer Grilling Masterclass Coming Soon",
    excerpt:
      "Join our expert chefs for an exclusive outdoor cooking workshop featuring BBQ techniques and seasonal recipes.",
    date: "2024-06-15",
    category: "Events",
    image: "/outdoor-grilling-bbq.jpg",
  },
  {
    id: "2",
    title: "New Mediterranean Recipe Collection",
    excerpt: "Explore our latest collection of authentic Mediterranean dishes, from Greek salads to Italian pasta.",
    date: "2024-06-12",
    category: "Recipes",
    image: "/mediterranean-platter.png",
  },
  {
    id: "3",
    title: "Community Cookbook Reaches 1000 Recipes",
    excerpt: "Our amazing community has contributed over 1000 unique recipes. Thank you for making FoodFusion special!",
    date: "2024-06-10",
    category: "Community",
    image: "/cookbook-recipes-collection.jpg",
  },
  {
    id: "4",
    title: "Healthy Meal Prep Tips for Busy Weeks",
    excerpt:
      "Learn how to prepare nutritious meals in advance with our comprehensive meal prep guide and time-saving strategies.",
    date: "2024-06-08",
    category: "Tips",
    image: "/meal-prep-guide.jpg",
  },
]

export const featuredRecipes: FeaturedRecipe[] = [
  {
    id: "1",
    title: "Classic Margherita Pizza",
    description: "Authentic Italian pizza with fresh mozzarella, basil, and homemade tomato sauce",
    image: "/margherita-pizza-fresh-basil.jpg",
    cookTime: "30 mins",
    difficulty: "Medium",
  },
  {
    id: "2",
    title: "Thai Green Curry",
    description: "Aromatic and spicy curry with coconut milk, vegetables, and fragrant herbs",
    image: "/thai-green-curry-coconut.jpg",
    cookTime: "45 mins",
    difficulty: "Medium",
  },
  {
    id: "3",
    title: "Chocolate Lava Cake",
    description: "Decadent dessert with a molten chocolate center and vanilla ice cream",
    image: "/chocolate-lava-cake-molten-center.jpg",
    cookTime: "25 mins",
    difficulty: "Hard",
  },
  {
    id: "4",
    title: "Caesar Salad",
    description: "Crisp romaine lettuce with parmesan, croutons, and creamy Caesar dressing",
    image: "/caesar-salad-parmesan-croutons.jpg",
    cookTime: "15 mins",
    difficulty: "Easy",
  },
  {
    id: "5",
    title: "Beef Tacos",
    description: "Seasoned ground beef with fresh toppings in crispy or soft tortillas",
    image: "/beef-tacos-fresh-toppings.jpg",
    cookTime: "20 mins",
    difficulty: "Easy",
  },
]

export const recipes: Recipe[] = [
  {
    id: "1",
    title: "Classic Margherita Pizza",
    description: "Authentic Italian pizza with fresh mozzarella, basil, and homemade tomato sauce",
    image: "/margherita-pizza-fresh-basil.jpg",
    cookTime: "15 mins",
    prepTime: "15 mins",
    servings: 4,
    difficulty: "Medium",
    cuisine: "Italian",
    dietary: ["Vegetarian"],
    ingredients: ["Pizza dough", "Tomato sauce", "Fresh mozzarella", "Fresh basil", "Olive oil", "Salt"],
    instructions: [
      "Preheat oven to 475°F (245°C)",
      "Roll out pizza dough on a floured surface",
      "Spread tomato sauce evenly",
      "Add mozzarella cheese",
      "Bake for 12-15 minutes until crust is golden",
      "Top with fresh basil and drizzle with olive oil",
    ],
    author: "Chef Marco",
    rating: 4.8,
    reviews: 234,
  },
  {
    id: "2",
    title: "Thai Green Curry",
    description: "Aromatic and spicy curry with coconut milk, vegetables, and fragrant herbs",
    image: "/thai-green-curry-coconut.jpg",
    cookTime: "30 mins",
    prepTime: "15 mins",
    servings: 4,
    difficulty: "Medium",
    cuisine: "Thai",
    dietary: ["Gluten-Free", "Dairy-Free"],
    ingredients: [
      "Green curry paste",
      "Coconut milk",
      "Chicken or tofu",
      "Thai basil",
      "Bell peppers",
      "Bamboo shoots",
    ],
    instructions: [
      "Heat oil in a large pan",
      "Add curry paste and cook for 1 minute",
      "Pour in coconut milk and bring to simmer",
      "Add protein and vegetables",
      "Cook for 20 minutes until tender",
      "Garnish with Thai basil",
    ],
    author: "Chef Somchai",
    rating: 4.7,
    reviews: 189,
  },
  {
    id: "3",
    title: "Chocolate Lava Cake",
    description: "Decadent dessert with a molten chocolate center and vanilla ice cream",
    image: "/chocolate-lava-cake-molten-center.jpg",
    cookTime: "12 mins",
    prepTime: "13 mins",
    servings: 4,
    difficulty: "Hard",
    cuisine: "French",
    dietary: ["Vegetarian"],
    ingredients: ["Dark chocolate", "Butter", "Eggs", "Sugar", "Flour", "Vanilla extract"],
    instructions: [
      "Preheat oven to 425°F (220°C)",
      "Melt chocolate and butter together",
      "Whisk eggs and sugar until thick",
      "Fold in chocolate mixture and flour",
      "Pour into greased ramekins",
      "Bake for 12 minutes until edges are firm",
    ],
    author: "Chef Pierre",
    rating: 4.9,
    reviews: 312,
  },
  {
    id: "4",
    title: "Caesar Salad",
    description: "Crisp romaine lettuce with parmesan, croutons, and creamy Caesar dressing",
    image: "/caesar-salad-parmesan-croutons.jpg",
    cookTime: "0 mins",
    prepTime: "15 mins",
    servings: 4,
    difficulty: "Easy",
    cuisine: "American",
    dietary: ["Vegetarian"],
    ingredients: ["Romaine lettuce", "Parmesan cheese", "Croutons", "Caesar dressing", "Lemon juice", "Black pepper"],
    instructions: [
      "Wash and chop romaine lettuce",
      "Make Caesar dressing with anchovies, garlic, and lemon",
      "Toss lettuce with dressing",
      "Add croutons and parmesan",
      "Season with black pepper",
      "Serve immediately",
    ],
    author: "Chef Julia",
    rating: 4.6,
    reviews: 156,
  },
  {
    id: "5",
    title: "Beef Tacos",
    description: "Seasoned ground beef with fresh toppings in crispy or soft tortillas",
    image: "/beef-tacos-fresh-toppings.jpg",
    cookTime: "15 mins",
    prepTime: "5 mins",
    servings: 4,
    difficulty: "Easy",
    cuisine: "Mexican",
    dietary: ["Gluten-Free"],
    ingredients: ["Ground beef", "Taco seasoning", "Tortillas", "Lettuce", "Tomatoes", "Cheese", "Sour cream"],
    instructions: [
      "Brown ground beef in a skillet",
      "Add taco seasoning and water",
      "Simmer for 5 minutes",
      "Warm tortillas",
      "Fill with beef and toppings",
      "Serve with lime wedges",
    ],
    author: "Chef Carlos",
    rating: 4.5,
    reviews: 201,
  },
  {
    id: "6",
    title: "Sushi Rolls",
    description: "Fresh sushi rolls with salmon, avocado, and cucumber",
    image: "/sushi-rolls-salmon-avocado.jpg",
    cookTime: "0 mins",
    prepTime: "30 mins",
    servings: 4,
    difficulty: "Hard",
    cuisine: "Japanese",
    dietary: ["Gluten-Free", "Dairy-Free"],
    ingredients: ["Sushi rice", "Nori sheets", "Fresh salmon", "Avocado", "Cucumber", "Rice vinegar"],
    instructions: [
      "Cook and season sushi rice",
      "Place nori on bamboo mat",
      "Spread rice evenly",
      "Add salmon, avocado, and cucumber",
      "Roll tightly using the mat",
      "Slice into pieces",
    ],
    author: "Chef Takeshi",
    rating: 4.8,
    reviews: 267,
  },
  {
    id: "7",
    title: "Greek Moussaka",
    description: "Layered eggplant casserole with spiced meat and béchamel sauce",
    image: "/greek-moussaka-eggplant.jpg",
    cookTime: "45 mins",
    prepTime: "30 mins",
    servings: 6,
    difficulty: "Hard",
    cuisine: "Greek",
    dietary: [],
    ingredients: ["Eggplant", "Ground lamb", "Tomatoes", "Onions", "Béchamel sauce", "Cinnamon"],
    instructions: [
      "Slice and salt eggplant, let drain",
      "Brown ground lamb with onions and spices",
      "Layer eggplant and meat in baking dish",
      "Prepare béchamel sauce",
      "Pour sauce over layers",
      "Bake at 350°F for 45 minutes",
    ],
    author: "Chef Dimitri",
    rating: 4.7,
    reviews: 143,
  },
  {
    id: "8",
    title: "Pad Thai",
    description: "Classic Thai stir-fried noodles with shrimp, peanuts, and tamarind sauce",
    image: "/pad-thai-noodles-shrimp.jpg",
    cookTime: "15 mins",
    prepTime: "15 mins",
    servings: 4,
    difficulty: "Medium",
    cuisine: "Thai",
    dietary: ["Gluten-Free", "Dairy-Free"],
    ingredients: ["Rice noodles", "Shrimp", "Eggs", "Bean sprouts", "Peanuts", "Tamarind paste"],
    instructions: [
      "Soak rice noodles in warm water",
      "Stir-fry shrimp until pink",
      "Push aside and scramble eggs",
      "Add noodles and sauce",
      "Toss with bean sprouts",
      "Top with peanuts and lime",
    ],
    author: "Chef Niran",
    rating: 4.6,
    reviews: 198,
  },
  {
    id: "9",
    title: "Chicken Tikka Masala",
    description: "Tender chicken in a creamy tomato-based curry sauce",
    image: "/chicken-tikka-masala-curry.jpg",
    cookTime: "30 mins",
    prepTime: "20 mins",
    servings: 4,
    difficulty: "Medium",
    cuisine: "Indian",
    dietary: ["Gluten-Free"],
    ingredients: ["Chicken breast", "Yogurt", "Tikka masala spices", "Tomato sauce", "Heavy cream", "Garam masala"],
    instructions: [
      "Marinate chicken in yogurt and spices",
      "Grill or pan-fry chicken pieces",
      "Make sauce with tomatoes and spices",
      "Add cream and simmer",
      "Add chicken to sauce",
      "Serve with rice or naan",
    ],
    author: "Chef Priya",
    rating: 4.9,
    reviews: 289,
  },
  {
    id: "10",
    title: "Vegan Buddha Bowl",
    description: "Nutritious bowl with quinoa, roasted vegetables, and tahini dressing",
    image: "/vegan-buddha-bowl-quinoa.jpg",
    cookTime: "25 mins",
    prepTime: "15 mins",
    servings: 2,
    difficulty: "Easy",
    cuisine: "American",
    dietary: ["Vegan", "Gluten-Free", "Dairy-Free"],
    ingredients: ["Quinoa", "Sweet potato", "Chickpeas", "Kale", "Avocado", "Tahini"],
    instructions: [
      "Cook quinoa according to package",
      "Roast sweet potato and chickpeas",
      "Massage kale with lemon juice",
      "Arrange ingredients in bowl",
      "Make tahini dressing",
      "Drizzle and serve",
    ],
    author: "Chef Emma",
    rating: 4.7,
    reviews: 176,
  },
  {
    id: "11",
    title: "French Onion Soup",
    description: "Rich beef broth with caramelized onions and melted Gruyère cheese",
    image: "/french-onion-soup-cheese.jpg",
    cookTime: "60 mins",
    prepTime: "15 mins",
    servings: 4,
    difficulty: "Medium",
    cuisine: "French",
    dietary: ["Vegetarian"],
    ingredients: ["Onions", "Beef broth", "Gruyère cheese", "Baguette", "Butter", "Thyme"],
    instructions: [
      "Caramelize onions slowly in butter",
      "Add broth and simmer for 30 minutes",
      "Toast baguette slices",
      "Ladle soup into oven-safe bowls",
      "Top with bread and cheese",
      "Broil until cheese is bubbly",
    ],
    author: "Chef Antoine",
    rating: 4.8,
    reviews: 221,
  },
  {
    id: "12",
    title: "Korean Bibimbap",
    description: "Mixed rice bowl with vegetables, egg, and spicy gochujang sauce",
    image: "/korean-bibimbap-rice-bowl.jpg",
    cookTime: "20 mins",
    prepTime: "25 mins",
    servings: 4,
    difficulty: "Medium",
    cuisine: "Korean",
    dietary: ["Gluten-Free"],
    ingredients: ["Rice", "Beef or tofu", "Spinach", "Carrots", "Bean sprouts", "Gochujang", "Egg"],
    instructions: [
      "Cook rice and keep warm",
      "Sauté each vegetable separately",
      "Cook beef or tofu with marinade",
      "Fry eggs sunny-side up",
      "Arrange ingredients over rice",
      "Serve with gochujang sauce",
    ],
    author: "Chef Min-ji",
    rating: 4.7,
    reviews: 203,
  },
]
